### ISSUE TITLE
Unhandled exception

### ISSUE THREAD

**Issue by Zorbaq** [Pathfinder-WOTR-Modding-Community/ModFinder#31]
First run, fails on prompt for WOTR path:

Application: ModFinder.exe
CoreCLR Version: 5.0.721.25508
.NET Version: 5.0.7
Description: The process was terminated due to an unhandled exception.
Exception Info: System.TypeInitializationException: The type initializer for 'ModFinder.Util.Logger' threw an exception.
 ---> System.TypeInitializationException: The type initializer for 'ModFinder.Main' threw an exception.
 ---> System.ArgumentNullException: Value cannot be null. (Parameter 'window')
   at System.Windows.Interop.WindowInteropHelper..ctor(Window window)
   at System.Windows.MessageBox.Show(Window owner, String messageBoxText, String caption, MessageBoxButton button, MessageBoxImage icon)
   at ModFinder.MainWindow.ShowError(String message) in D:\a\ModFinder\ModFinder\ModFinderClient\MainWindow.xaml.cs:line 429
   at ModFinder.Util.Logger.Error(String log, Exception e) in D:\a\ModFinder\ModFinder\ModFinderClient\Util\Logger.cs:line 47
   at ModFinder.Main.get_WrathPath() in D:\a\ModFinder\ModFinder\ModFinderClient\Main.cs:line 145
   at ModFinder.Main..cctor() in D:\a\ModFinder\ModFinder\ModFinderClient\Main.cs:line 158
   --- End of inner exception stack trace ---
   at ModFinder.Main.get_AppFolder() in D:\a\ModFinder\ModFinder\ModFinderClient\Main.cs:line 31
   at ModFinder.Util.Logger..cctor() in D:\a\ModFinder\ModFinder\ModFinderClient\Util\Logger.cs:line 11
   --- End of inner exception stack trace ---
   at ModFinder.Util.Logger.ProcessLogs(CancellationToken cancellationToken) in D:\a\ModFinder\ModFinder\ModFinderClient\Util\Logger.cs:line 62
   at ModFinder.Util.Logger.<.ctor>b__6_0() in D:\a\ModFinder\ModFinder\ModFinderClient\Util\Logger.cs:line 27
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

**Comment by WittleWolfie** [comment]
Fixed in next release.
