### ISSUE TITLE
Mod in game mod folder with empty Info.json causes CTD on Modfinder start

### ISSUE THREAD

**Issue by pheonix99** [Pathfinder-WOTR-Modding-Community/ModFinder#42]
What the title says. Discovered this by accident when I forgot to clean out a barely-started thing's auto-deploy

Two errors in log.
[1/2 01:24:46][E] System.NullReferenceException: Object reference not set to an instance of an object.
   at ModFinder.MainWindow.<>c__DisplayClass15_0.<SetModEnabled>b__0(XElement x) in D:\a\ModFinder\ModFinder\ModFinderClient\MainWindow.xaml.cs:line 382
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at ModFinder.MainWindow.SetModEnabled(ModViewModel modVM, Boolean enabled) in D:\a\ModFinder\ModFinder\ModFinderClient\MainWindow.xaml.cs:line 382

[1/2 01:24:49][E] System.InvalidOperationException: Failed to compare two elements in the array.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at ModFinder.UI.ModSort.CompareStatus(ModViewModel x, ModViewModel y) in D:\a\ModFinder\ModFinder\ModFinderClient\UI\ModSort.cs:line 63
   at ModFinder.UI.ModSort.Compare(ModViewModel x, ModViewModel y) in D:\a\ModFinder\ModFinder\ModFinderClient\UI\ModSort.cs:line 42
   at System.Collections.Generic.ArraySortHelper`1.InsertionSort(Span`1 keys, Comparison`1 comparer)
   at System.Collections.Generic.ArraySortHelper`1.IntroSort(Span`1 keys, Int32 depthLimit, Comparison`1 comparer)
   at System.Collections.Generic.ArraySortHelper`1.IntroSort(Span`1 keys, Int32 depthLimit, Comparison`1 comparer)
   at System.Collections.Generic.ArraySortHelper`1.IntrospectiveSort(Span`1 keys, Comparison`1 comparer)
   at System.Collections.Generic.ArraySortHelper`1.Sort(Span`1 keys, IComparer`1 comparer)
   --- End of inner exception stack trace ---
   at System.Collections.Generic.ArraySortHelper`1.Sort(Span`1 keys, IComparer`1 comparer)
   at System.Array.Sort[T](T[] array, Int32 index, Int32 length, IComparer`1 comparer)
   at System.Collections.Generic.List`1.Sort(Int32 index, Int32 count, IComparer`1 comparer)
   at System.Collections.Generic.List`1.Sort(IComparer`1 comparer)
   at ModFinder.UI.ModDatabase.InitSort() in D:\a\ModFinder\ModFinder\ModFinderClient\UI\ModDatabase.cs:line 59
   at ModFinder.MainWindow..ctor() in D:\a\ModFinder\ModFinder\ModFinderClient\MainWindow.xaml.cs:line 97

**Comment by WittleWolfie** [comment]
Fixed in 1.3.7
