### ISSUE TITLE
Updating Respec Mod to 1.10.12 breaks ModFinder

### ISSUE THREAD

**Issue by pheonix99** [Pathfinder-WOTR-Modding-Community/ModFinder#46]
Installing the newest Respec Mod update causes many other mods to stop being handled

[2/4 01:55:04][I] Found installed mod: C:\Program Files (x86)\Steam\steamapps\common\Pathfinder Second Adventure\Mods\RespecWrath
[2/4 01:55:04][I] Respec Mod has no required modes.
[2/4 01:55:04][E] Failed to check installed mods.
[2/4 01:55:04][E] System.ArgumentException: An item with the same key has already been added. Key: RespecWrath-UMM
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at ModFinder.MainWindow.CheckInstalledModsInternal() in D:\a\ModFinder\ModFinder\ModFinderClient\MainWindow.xaml.cs:line 239

**Comment by WittleWolfie** [comment]
This happens because there's some issue w/ naming. If you've manually installed RespecWrath then it'll be called `RespecWrath-DownloadThis`, but ModFinder installs it as `RespecWrath`. Go to your mods, delete `RespecWrath-DownloadThis`, and everything should work (including future updates).
