### ISSUE TITLE
Failed to check installed mods

### ISSUE THREAD

**Issue by os-banta** [Pathfinder-WOTR-Modding-Community/ModFinder#54]
Whenever opening or rechecking installed mods I get this error, and don't know where to go from here.
[Log.txt](https://github.com/Pathfinder-WOTR-Modding-Community/ModFinder/files/11066042/Log.txt)
[3/24 03:37:42][I] Respec Mod has no required modes.
[3/24 03:37:42][E] Failed to check installed mods.
[3/24 03:37:42][E] System.ArgumentException: An item with the same key has already been added. Key: RespecWrath-UMM
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at ModFinder.MainWindow.CheckInstalledModsInternal() in D:\a\ModFinder\ModFinder\ModFinderClient\MainWindow.xaml.cs:line 237

**Comment by WittleWolfie** [comment]
Go to your mods folder and delete both copies of `RespecWrath`, then re-install using ModFinder. This happens when you end up with two copies of a mod installed since ModFinder doesn't know which one to use.
